server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG

ws:
  topics:
    not_active: "/topic/newrfidlabel"

spring:
  application:
    name: control-system
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: car_entry_control
        use_sql_comments: true
        format_sql: true
        criteria:
          literal_handling_mode: BIND
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/unit_techno?currentSchema=car_entry_control
    username: car_entry_admin
    password: squd